'use client';

import React, { useState } from 'react';
import { AppHeader } from '@/components/layout/AppHeader';
import { Dashboard } from '@/components/features/Dashboard';
import { Upload } from '@/components/features/Upload';
import { Processing } from '@/components/features/Processing';
import { JobPackEditor } from '@/components/features/JobPackEditor';
import { ExportScreen } from '@/components/features/ExportScreen';
import jsPDF from 'jspdf';

export default function HomePageClient() {
  const [activeScreen, setActiveScreen] = useState('dash');
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [jobData, setJobData] = useState<any>(null);

  const onNavigate = (screen: string) => {
    setActiveScreen(screen);
  };

  const onBeginProcessing = (file: File) => {
    setUploadFile(file);
    setActiveScreen('proc');
  };

  const onExtractionComplete = (data: any) => {
    if (data) {
      setJobData(data);
    }
    setActiveScreen('pack');
  };

  const generatePDF = () => {
    const data = jobData || {};
    const md = data.metadata || {};
    const wd = data.wellData || {};

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
    const PW = 215.9, PH = 279.4, M = 14, CW = PW - M * 2;
    const ORG = [232, 119, 12], LG = [242, 242, 242], DK = [26, 26, 26], WH = [255, 255, 255], BD = [180, 180, 180], HG = [235, 235, 235];

    const chrome = (pg: number, tot: number) => {
      // @ts-ignore
      doc.setFillColor(...ORG); doc.rect(M, 6, CW, 8, 'F');
      doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(255, 255, 255);
      doc.text('IMPORT TOOL CORPORATION LTD.', M + 3, 10.5); 
      doc.text('LINER HANGER PROGRAM', PW - M - 3, 10.5, { align: 'right' });
      
      doc.setFont('helvetica', 'normal'); doc.setFontSize(6.5);
      doc.text('First in Service, First in Quality Tools  |  www.importtool.com  |  Certified ISO 9001:2015', M + 3, 13.5);
      doc.text(`PAGE ${pg} OF ${tot}`, PW - M - 3, 13.5, { align: 'right' });
      
      // @ts-ignore
      doc.setFillColor(...LG); doc.rect(M, PH - 11, CW, 6, 'F');
      doc.setFontSize(6); doc.setTextColor(130, 130, 130);
      doc.text('CALGARY, AB: 403.261.3032  |  EDMONTON, AB: 780.434.6406  |  ESTEVAN, SK: 306.634.2511  |  PARADISE, NL: 709.748.4990', PW / 2, PH - 7.5, { align: 'center' });
      doc.setFontSize(5.5); doc.text('Generated by Amazing Business Results AI · amazingbusinessresults.com', PW / 2, PH - 4, { align: 'center' });
    };

    const sh = (txt: string, y: number) => {
      // @ts-ignore
      doc.setFillColor(...ORG); doc.rect(M, y, CW, 6, 'F'); 
      doc.setFont('helvetica', 'bold'); doc.setFontSize(8); doc.setTextColor(255, 255, 255);
      doc.text(txt, M + 3, y + 4.2); 
      
      // RESET font style so subsequent text isn't white!
      doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(40,40,40);
      return y + 6;
    };

    chrome(1, 1);
    let y = 22;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.setTextColor(26, 26, 26);
    doc.text('LINER HANGER PROGRAM', M, y); y += 7;

    doc.setFontSize(10);
    doc.text(`WELL NAME: ${md.wellName || 'N/A'}`, M, y); y += 6;
    doc.text(`QUOTE NO: ${md.quoteNo || 'N/A'}`, M, y); y += 6;
    doc.text(`CUSTOMER: ${md.customer || 'N/A'}`, M, y); y += 6;
    
    y = sh('CASING INFORMATION', y) + 2;
    doc.text(`Production Liner: ${wd.linerTop || ''} – ${wd.td || ''} MD | ${wd.holeSize || ''}`, M, y + 4);
    y += 10;

    y = sh('LINER EQUIPMENT REQUIRED', y) + 2;
    const items = data.equipmentList || [];
    if(items.length > 0) {
      items.forEach((it: any, i: number) => {
        doc.text(`${i+1}. ${it.size || ''} ${it.description || ''}`, M, y + 4);
        y += 6;
      });
    } else {
       doc.text("No equipment listed", M, y + 4);
       y += 6;
    }
    
    y += 4;
    y = sh('RUNNING PROCEDURES', y) + 2;
    const steps = data.runningProcedures || [];
    if(steps.length > 0) {
      steps.forEach((it: any, i: number) => {
        const text = typeof it === 'string' ? it : it.content || '';
        const lines = doc.splitTextToSize(`- ${text}`, CW - 4);
        doc.text(lines, M, y + 4);
        y += (lines.length * 4) + 2;
      });
    } else {
       doc.text("No procedures provided", M, y + 4);
       y += 6;
    }

    doc.save(`JobPack_${md.wellName ? md.wellName.replace(/[^a-zA-Z0-9]/g, '_') : 'Export'}.pdf`);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', width: '100vw', overflow: 'hidden' }}>
      <AppHeader activeScreen={activeScreen} onNavigate={onNavigate} onExport={() => setActiveScreen('export')} />
      
      <div style={{ flex: 1, overflow: 'hidden', position: 'relative' }}>
        {activeScreen === 'dash' && <Dashboard onNavigate={onNavigate} />}
        {activeScreen === 'upload' && <Upload onBack={() => setActiveScreen('dash')} onBeginProcessing={onBeginProcessing} />}
        {activeScreen === 'proc' && <Processing file={uploadFile} onComplete={onExtractionComplete} onCancel={() => setActiveScreen('upload')} />}
        {activeScreen === 'pack' && <JobPackEditor data={jobData} onExport={(data: import('@/types').JobPack) => { setJobData(data); setActiveScreen('export'); }} />}
        {activeScreen === 'export' && <ExportScreen data={jobData} onBack={() => setActiveScreen('pack')} onGeneratePDF={generatePDF} />}
      </div>
    </div>
  );
}
